insert into banco (codigo, descricao) values ('246','Banco ABC Brasil S.A.');
insert into banco (codigo, descricao) values ('25','Banco Alfa S.A.');
insert into banco (codigo, descricao) values ('641','Banco Alvorada S.A.');
insert into banco (codigo, descricao) values ('29','Banco Banerj S.A.');
insert into banco (codigo, descricao) values ('0','Banco Bankpar S.A.');
insert into banco (codigo, descricao) values ('740','Banco Barclays S.A.');
insert into banco (codigo, descricao) values ('107','Banco BBM S.A.');
insert into banco (codigo, descricao) values ('31','Banco Beg S.A.');
insert into banco (codigo, descricao) values ('739','Banco BGN S.A.');
insert into banco (codigo, descricao) values ('96','Banco BM&F de Serviços de Liquidação e Custódia S.A');
insert into banco (codigo, descricao) values ('318','Banco BMG S.A.');
insert into banco (codigo, descricao) values ('752','Banco BNP Paribas Brasil S.A.');
insert into banco (codigo, descricao) values ('248','Banco Boavista Interatlântico S.A.');
insert into banco (codigo, descricao) values ('218','Banco Bonsucesso S.A.');
insert into banco (codigo, descricao) values ('65','Banco Bracce S.A.');
insert into banco (codigo, descricao) values ('36','Banco Bradesco BBI S.A.');
insert into banco (codigo, descricao) values ('204','Banco Bradesco Cartões S.A.');
insert into banco (codigo, descricao) values ('394','Banco Bradesco Financiamentos S.A.');
insert into banco (codigo, descricao) values ('237','Banco Bradesco S.A.');
insert into banco (codigo, descricao) values ('225','Banco Brascan S.A.');
insert into banco (codigo, descricao) values ('208','Banco BTG Pactual S.A.');
insert into banco (codigo, descricao) values ('44','Banco BVA S.A.');
insert into banco (codigo, descricao) values ('263','Banco Cacique S.A.');
insert into banco (codigo, descricao) values ('473','Banco Caixa Geral - Brasil S.A.');
insert into banco (codigo, descricao) values ('40','Banco Cargill S.A.');
insert into banco (codigo, descricao) values ('233','Banco Cifra S.A.');
insert into banco (codigo, descricao) values ('745','Banco Citibank S.A.');
insert into banco (codigo, descricao) values ('M08','Banco Citicard S.A.');
insert into banco (codigo, descricao) values ('M19','Banco CNH Capital S.A.');
insert into banco (codigo, descricao) values ('215','Banco Comercial e de Investimento Sudameris S.A.');
insert into banco (codigo, descricao) values ('756','Banco Cooperativo do Brasil S.A. - BANCOOB');
insert into banco (codigo, descricao) values ('748','Banco Cooperativo Sicredi S.A.');
insert into banco (codigo, descricao) values ('222','Banco Credit Agricole Brasil S.A.');
insert into banco (codigo, descricao) values ('505','Banco Credit Suisse (Brasil) S.A.');
insert into banco (codigo, descricao) values ('229','Banco Cruzeiro do Sul S.A.');
insert into banco (codigo, descricao) values ('','Banco CSF S.A.');
insert into banco (codigo, descricao) values ('3','Banco da Amazônia S.A.');
insert into banco (codigo, descricao) values ('083-3','Banco da China Brasil S.A.');
insert into banco (codigo, descricao) values ('707','Banco Daycoval S.A.');
insert into banco (codigo, descricao) values ('M06','Banco de Lage Landen Brasil S.A.');
insert into banco (codigo, descricao) values ('24','Banco de Pernambuco S.A. - BANDEPE');
insert into banco (codigo, descricao) values ('456','Banco de Tokyo-Mitsubishi UFJ Brasil S.A.');
insert into banco (codigo, descricao) values ('214','Banco Dibens S.A.');
insert into banco (codigo, descricao) values ('1','Banco do Brasil S.A.');
insert into banco (codigo, descricao) values ('47','Banco do Estado de Sergipe S.A.');
insert into banco (codigo, descricao) values ('37','Banco do Estado do Pará S.A.');
insert into banco (codigo, descricao) values ('41','Banco do Estado do Rio Grande do Sul S.A.');
insert into banco (codigo, descricao) values ('4','Banco do Nordeste do Brasil S.A.');
insert into banco (codigo, descricao) values ('265','Banco Fator S.A.');
insert into banco (codigo, descricao) values ('M03','Banco Fiat S.A.');
insert into banco (codigo, descricao) values ('224','Banco Fibra S.A.');
insert into banco (codigo, descricao) values ('626','Banco Ficsa S.A.');
insert into banco (codigo, descricao) values ('','Banco Fidis S.A.');
insert into banco (codigo, descricao) values ('394','Banco Finasa BMC S.A.');
insert into banco (codigo, descricao) values ('M18','Banco Ford S.A.');
insert into banco (codigo, descricao) values ('M07','Banco GMAC S.A.');
insert into banco (codigo, descricao) values ('612','Banco Guanabara S.A.');
insert into banco (codigo, descricao) values ('M22','Banco Honda S.A.');
insert into banco (codigo, descricao) values ('63','Banco Ibi S.A. Banco Múltiplo');
insert into banco (codigo, descricao) values ('M11','Banco IBM S.A.');
insert into banco (codigo, descricao) values ('604','Banco Industrial do Brasil S.A.');
insert into banco (codigo, descricao) values ('320','Banco Industrial e Comercial S.A.');
insert into banco (codigo, descricao) values ('653','Banco Indusval S.A.');
insert into banco (codigo, descricao) values ('249','Banco Investcred Unibanco S.A.');
insert into banco (codigo, descricao) values ('184','Banco Itaú BBA S.A.');
insert into banco (codigo, descricao) values ('479','Banco ItaúBank S.A');
insert into banco (codigo, descricao) values ('','Banco Itaucard S.A.');
insert into banco (codigo, descricao) values ('M09','Banco Itaucred Financiamentos S.A.');
insert into banco (codigo, descricao) values ('376','Banco J. P. Morgan S.A.');
insert into banco (codigo, descricao) values ('74','Banco J. Safra S.A.');
insert into banco (codigo, descricao) values ('217','Banco John Deere S.A.');
insert into banco (codigo, descricao) values ('600','Banco Luso Brasileiro S.A.');
insert into banco (codigo, descricao) values ('389','Banco Mercantil do Brasil S.A.');
insert into banco (codigo, descricao) values ('746','Banco Modal S.A.');
insert into banco (codigo, descricao) values ('45','Banco Opportunity S.A.');
insert into banco (codigo, descricao) values ('79','Banco Original do Agronegócio S.A.');
insert into banco (codigo, descricao) values ('623','Banco Panamericano S.A.');
insert into banco (codigo, descricao) values ('611','Banco Paulista S.A.');
insert into banco (codigo, descricao) values ('643','Banco Pine S.A.');
insert into banco (codigo, descricao) values ('638','Banco Prosper S.A.');
insert into banco (codigo, descricao) values ('747','Banco Rabobank International Brasil S.A.');
insert into banco (codigo, descricao) values ('356','Banco Real S.A.');
insert into banco (codigo, descricao) values ('633','Banco Rendimento S.A.');
insert into banco (codigo, descricao) values ('M16','Banco Rodobens S.A.');
insert into banco (codigo, descricao) values ('72','Banco Rural Mais S.A.');
insert into banco (codigo, descricao) values ('453','Banco Rural S.A.');
insert into banco (codigo, descricao) values ('422','Banco Safra S.A.');
insert into banco (codigo, descricao) values ('33','Banco Santander (Brasil) S.A.');
insert into banco (codigo, descricao) values ('250','Banco Schahin S.A.');
insert into banco (codigo, descricao) values ('749','Banco Simples S.A.');
insert into banco (codigo, descricao) values ('366','Banco Société Générale Brasil S.A.');
insert into banco (codigo, descricao) values ('637','Banco Sofisa S.A.');
insert into banco (codigo, descricao) values ('12','Banco Standard de Investimentos S.A.');
insert into banco (codigo, descricao) values ('464','Banco Sumitomo Mitsui Brasileiro S.A.');
insert into banco (codigo, descricao) values ('082-5','Banco Topázio S.A.');
insert into banco (codigo, descricao) values ('M20','Banco Toyota do Brasil S.A.');
insert into banco (codigo, descricao) values ('634','Banco Triângulo S.A.');
insert into banco (codigo, descricao) values ('M14','Banco Volkswagen S.A.');
insert into banco (codigo, descricao) values ('M23','Banco Volvo (Brasil) S.A.');
insert into banco (codigo, descricao) values ('655','Banco Votorantim S.A.');
insert into banco (codigo, descricao) values ('610','Banco VR S.A.');
insert into banco (codigo, descricao) values ('119','Banco Western Union do Brasil S.A.');
insert into banco (codigo, descricao) values ('370','Banco WestLB do Brasil S.A.');
insert into banco (codigo, descricao) values ('','Banco Yamaha Motor S.A.');
insert into banco (codigo, descricao) values ('21','BANESTES S.A. Banco do Estado do Espírito Santo');
insert into banco (codigo, descricao) values ('719','Banif-Banco Internacional do Funchal (Brasil)S.A.');
insert into banco (codigo, descricao) values ('755','Bank of America Merrill Lynch Banco Múltiplo S.A.');
insert into banco (codigo, descricao) values ('73','BB Banco Popular do Brasil S.A.');
insert into banco (codigo, descricao) values ('78','BES Investimento do Brasil S.A.-Banco de Investimento');
insert into banco (codigo, descricao) values ('69','BPN Brasil Banco Múltiplo S.A.');
insert into banco (codigo, descricao) values ('70','BRB - Banco de Brasília S.A.');
insert into banco (codigo, descricao) values ('104','Caixa Econômica Federal');
insert into banco (codigo, descricao) values ('477','Citibank S.A.');
insert into banco (codigo, descricao) values ('081-7','Concórdia Banco S.A.');
insert into banco (codigo, descricao) values ('487','Deutsche Bank S.A. - Banco Alemão');
insert into banco (codigo, descricao) values ('64','Goldman Sachs do Brasil Banco Múltiplo S.A.');
insert into banco (codigo, descricao) values ('62','Hipercard Banco Múltiplo S.A.');
insert into banco (codigo, descricao) values ('399','HSBC Bank Brasil S.A. - Banco Múltiplo');
insert into banco (codigo, descricao) values ('492','ING Bank N.V.');
insert into banco (codigo, descricao) values ('652','Itaú Unibanco Holding S.A.');
insert into banco (codigo, descricao) values ('341','Itaú Unibanco S.A.');
insert into banco (codigo, descricao) values ('488','JPMorgan Chase Bank');
insert into banco (codigo, descricao) values ('751','Scotiabank Brasil S.A. Banco Múltiplo');
insert into banco (codigo, descricao) values ('','Standard Chartered Bank (Brasil) S/A–Bco Invest.');
insert into banco (codigo, descricao) values ('409','UNIBANCO - União de Bancos Brasileiros S.A.');
insert into banco (codigo, descricao) values ('230','Unicard Banco Múltiplo S.A.');